import { fetchUser } from "@/lib/fetchUser"

export default function Profile({ params }: { params: { id: string } }) {
  const user = fetchUser(params.id)

  if (!user) return <p>Profile does not exist !</p>

  return (
    <div>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fermentum leo vel orci porta non pulvinar neque laoreet. Mi proin sed libero enim sed faucibus turpis in eu. Ut diam quam nulla porttitor. Dolor sit amet consectetur adipiscing elit. Rhoncus urna neque viverra justo nec ultrices dui sapien eget. Tortor at risus viverra adipiscing at in tellus integer feugiat. Sed adipiscing diam donec adipiscing tristique risus nec. Nisl suscipit adipiscing bibendum est. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Etiam tempor orci eu lobortis elementum. Id faucibus nisl tincidunt eget nullam non. Sed libero enim sed faucibus. Suspendisse in est ante in nibh mauris cursus mattis molestie. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla.

      Nunc sed id semper risus in hendrerit gravida rutrum. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Morbi leo urna molestie at elementum eu facilisis sed. Pellentesque sit amet porttitor eget dolor morbi non. Amet tellus cras adipiscing enim. Facilisis leo vel fringilla est ullamcorper eget. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Nec ultrices dui sapien eget mi proin sed. Nisl pretium fusce id velit ut tortor. Risus ultricies tristique nulla aliquet enim tortor. Mattis molestie a iaculis at erat. Lobortis mattis aliquam faucibus purus in. Aliquet lectus proin nibh nisl condimentum id. Laoreet id donec ultrices tincidunt arcu non sodales neque. Nunc lobortis mattis aliquam faucibus purus in massa tempor. Ornare aenean euismod elementum nisi quis eleifend quam. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper.

      Nibh mauris cursus mattis molestie a iaculis. Viverra aliquet eget sit amet tellus cras adipiscing enim. Feugiat vivamus at augue eget arcu dictum varius duis. Tincidunt dui ut ornare lectus sit amet. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Morbi leo urna molestie at elementum eu facilisis. Risus in hendrerit gravida rutrum quisque non. Tincidunt praesent semper feugiat nibh sed pulvinar. Vitae semper quis lectus nulla at volutpat. Scelerisque fermentum dui faucibus in. Diam maecenas sed enim ut sem viverra aliquet eget sit. Et pharetra pharetra massa massa.

      In hac habitasse platea dictumst quisque. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Elementum curabitur vitae nunc sed velit dignissim sodales ut eu. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero id. In ornare quam viverra orci sagittis eu volutpat odio. Diam sollicitudin tempor id eu nisl nunc. Scelerisque viverra mauris in aliquam sem fringilla ut morbi. Adipiscing elit duis tristique sollicitudin nibh sit. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Senectus et netus et malesuada fames ac turpis. Tortor consequat id porta nibh venenatis cras sed felis eget. Est velit egestas dui id ornare arcu odio ut sem. Cras adipiscing enim eu turpis. At varius vel pharetra vel turpis nunc eget lorem.

      Blandit turpis cursus in hac habitasse platea dictumst quisque. Etiam sit amet nisl purus in mollis. Id diam maecenas ultricies mi eget mauris pharetra et. Morbi tempus iaculis urna id. Ornare quam viverra orci sagittis eu volutpat odio. Aliquet bibendum enim facilisis gravida neque convallis. Ullamcorper eget nulla facilisi etiam dignissim. Amet volutpat consequat mauris nunc congue nisi vitae suscipit tellus. In aliquam sem fringilla ut morbi tincidunt augue. Tristique et egestas quis ipsum suspendisse ultrices gravida. At quis risus sed vulputate odio ut enim blandit volutpat. Diam sit amet nisl suscipit adipiscing bibendum est. Faucibus purus in massa tempor nec.

      Volutpat diam ut venenatis tellus in. Dolor sed viverra ipsum nunc aliquet bibendum enim. Aliquam etiam erat velit scelerisque in. Tellus elementum sagittis vitae et leo. Nunc pulvinar sapien et ligula. Arcu non sodales neque sodales ut etiam sit. Ac tortor dignissim convallis aenean et tortor at risus. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Et tortor consequat id porta nibh. Vivamus at augue eget arcu dictum varius. Velit euismod in pellentesque massa. Nibh cras pulvinar mattis nunc sed blandit libero volutpat. Feugiat vivamus at augue eget arcu dictum varius. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. In pellentesque massa placerat duis. Mauris cursus mattis molestie a iaculis. At quis risus sed vulputate odio.

      Laoreet sit amet cursus sit. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Tellus elementum sagittis vitae et leo duis ut diam quam. Molestie a iaculis at erat pellentesque adipiscing. Amet dictum sit amet justo donec. Risus commodo viverra maecenas accumsan lacus vel facilisis. Curabitur vitae nunc sed velit dignissim. Sit amet aliquam id diam maecenas ultricies mi. Nulla porttitor massa id neque aliquam vestibulum morbi. Cras fermentum odio eu feugiat pretium nibh. Faucibus scelerisque eleifend donec pretium. Tincidunt lobortis feugiat vivamus at augue eget arcu. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi.

      Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Nunc aliquet bibendum enim facilisis. Sed viverra ipsum nunc aliquet bibendum enim. Massa enim nec dui nunc mattis enim ut tellus elementum. Adipiscing tristique risus nec feugiat in fermentum. Sit amet purus gravida quis blandit. Porta nibh venenatis cras sed felis eget velit aliquet. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Blandit cursus risus at ultrices. Tristique senectus et netus et. Lorem dolor sed viverra ipsum nunc aliquet bibendum. A iaculis at erat pellentesque adipiscing commodo elit at imperdiet.

      Nulla facilisi nullam vehicula ipsum a arcu. Et ultrices neque ornare aenean euismod elementum. Porttitor massa id neque aliquam vestibulum. Aliquam nulla facilisi cras fermentum odio eu feugiat. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Suscipit tellus mauris a diam. Scelerisque felis imperdiet proin fermentum leo vel orci porta. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Sed elementum tempus egestas sed sed risus. Et netus et malesuada fames ac turpis egestas sed. In massa tempor nec feugiat nisl pretium fusce. Eget magna fermentum iaculis eu.

      Habitasse platea dictumst quisque sagittis purus sit amet volutpat. Nulla at volutpat diam ut. Est placerat in egestas erat imperdiet sed. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Elementum facilisis leo vel fringilla est ullamcorper eget. Arcu vitae elementum curabitur vitae. Non sodales neque sodales ut. Ultricies mi quis hendrerit dolor. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. Vitae ultricies leo integer malesuada nunc vel risus. Rutrum quisque non tellus orci. Vulputate eu scelerisque felis imperdiet proin fermentum leo. Pellentesque diam volutpat commodo sed egestas egestas fringilla. Aliquet eget sit amet tellus cras. Sed elementum tempus egestas sed sed risus pretium. Malesuada bibendum arcu vitae elementum curabitur. Mattis vulputate enim nulla aliquet porttitor.

      Augue lacus viverra vitae congue eu. Malesuada proin libero nunc consequat interdum. A diam maecenas sed enim ut sem viverra aliquet eget. Pellentesque pulvinar pellentesque habitant morbi tristique. Iaculis eu non diam phasellus vestibulum. Montes nascetur ridiculus mus mauris. Proin libero nunc consequat interdum varius. Aliquam faucibus purus in massa tempor nec feugiat. Tortor posuere ac ut consequat. Ac ut consequat semper viverra nam libero justo. Eu mi bibendum neque egestas congue quisque. Quis ipsum suspendisse ultrices gravida dictum. Massa enim nec dui nunc mattis. Aliquam nulla facilisi cras fermentum odio eu. Arcu ac tortor dignissim convallis aenean et tortor at risus. Ultricies mi quis hendrerit dolor. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. In cursus turpis massa tincidunt dui ut ornare lectus.

      Eu non diam phasellus vestibulum lorem sed risus ultricies. Iaculis nunc sed augue lacus viverra vitae congue. Semper auctor neque vitae tempus quam pellentesque. Scelerisque fermentum dui faucibus in ornare quam viverra. Nunc eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Turpis egestas integer eget aliquet nibh praesent tristique. Euismod elementum nisi quis eleifend quam adipiscing. Eget mi proin sed libero. Vivamus arcu felis bibendum ut tristique et. Neque vitae tempus quam pellentesque nec nam aliquam. In ornare quam viverra orci sagittis eu volutpat. Sed nisi lacus sed viverra tellus in hac. Amet mauris commodo quis imperdiet massa tincidunt nunc. In mollis nunc sed id semper risus in hendrerit gravida. Vulputate mi sit amet mauris commodo quis imperdiet. In ornare quam viverra orci.

      Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Morbi tincidunt ornare massa eget egestas purus. Auctor neque vitae tempus quam pellentesque nec nam. Sapien eget mi proin sed libero enim. Tempor orci eu lobortis elementum nibh tellus molestie nunc. Felis donec et odio pellentesque diam volutpat commodo. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Sed blandit libero volutpat sed. Lorem sed risus ultricies tristique. Enim nunc faucibus a pellentesque sit amet porttitor eget. Sapien eget mi proin sed libero enim sed. Odio pellentesque diam volutpat commodo sed egestas. Mattis vulputate enim nulla aliquet. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Natoque penatibus et magnis dis parturient montes. Vitae semper quis lectus nulla at volutpat. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Pellentesque adipiscing commodo elit at imperdiet. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus.
    </div>
  )
}   